version: "3.8"
services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: 
    - sh
    - -c
    - >
      until nc -z db 3306; do echo "⏳ waiting for db..."; sleep 2; done;
      python migrations/run_migrations.py &&
      streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    container_name: streamlit-app
    depends_on:
        - db
    ports:
      - "8501:8501"
    environment:
      DATABASE_URL: "mysql+pymysql://testuser:testpass@db:3306/testdb"

volumes:
  db_data:
 
    