version: "3.8"
services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3307:3306"
    volumes:
      - ./data/db/mysql:/var/lib/mysql

  app:
    build: .
    container_name: streamlit-app
    #command: "sh -c until nc -z db 3306; do echo '⏳ waiting for db...';  sleep 2; done && python migrations/run_migration; streamlit run app.py"
    depends_on:
        - db
    ports:
      - "8500:8501"

 
    