# Use official Playwright image with browsers installed
FROM mcr.microsoft.com/playwright/python:v1.47.0-focal

WORKDIR /usr/src/app

# Copy dependencies first
COPY requirements.txt .

# Install deps
RUN pip install --no-cache-dir -r requirements.txt pytest

# Copy the whole project (includes app.py, tests/, migrations/, etc.)
COPY . .

# Just to debug – list files inside image
RUN ls -R /usr/src/app

# Default command: run pytest on tests/
CMD ["pytest", "-v", "tests/"]

